// <auto-generated />
using System;
using DoAnMangMayTinh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnMangMayTinh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnMangMayTinh.Models.DangKy", b =>
                {
                    b.Property<int>("ID_DK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DK"));

                    b.Property<int>("ID_Lich")
                        .HasColumnType("int");

                    b.Property<int>("ID_SV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_DK");

                    b.HasIndex("ID_Lich");

                    b.HasIndex("ID_SV");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.GiaoVien", b =>
                {
                    b.Property<int>("ID_GV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_GV"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("ID_GV");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.KyThi", b =>
                {
                    b.Property<int>("ID_KyThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_KyThi"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_KyThi");

                    b.ToTable("KyThis");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.LichThi", b =>
                {
                    b.Property<int>("ID_Lich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Lich"));

                    b.Property<TimeSpan>("GioThi")
                        .HasColumnType("time");

                    b.Property<int>("ID_KyThi")
                        .HasColumnType("int");

                    b.Property<int>("ID_Mon")
                        .HasColumnType("int");

                    b.Property<int>("ID_Phong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Lich");

                    b.HasIndex("ID_KyThi");

                    b.HasIndex("ID_Mon");

                    b.HasIndex("ID_Phong");

                    b.ToTable("LichThis");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.MonThi", b =>
                {
                    b.Property<int>("ID_Mon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Mon"));

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Mon");

                    b.ToTable("MonThis");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.PhanCong", b =>
                {
                    b.Property<int>("ID_PC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PC"));

                    b.Property<int>("ID_GV")
                        .HasColumnType("int");

                    b.Property<int>("ID_Lich")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PC");

                    b.HasIndex("ID_GV");

                    b.HasIndex("ID_Lich");

                    b.ToTable("PhanCongs", t =>
                        {
                            t.HasCheckConstraint("CK_VaiTro", "VaiTro IN ('Ra đề', 'Coi thi')");
                        });
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.PhongThi", b =>
                {
                    b.Property<int>("ID_Phong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Phong"));

                    b.Property<int>("SoLuongChoNgoi")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Phong");

                    b.ToTable("PhongThis");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.SinhVien", b =>
                {
                    b.Property<int>("ID_SV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SV"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_SV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ID_GV")
                        .HasColumnType("int");

                    b.Property<int?>("ID_SV")
                        .HasColumnType("int");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("ID_GV");

                    b.HasIndex("ID_SV");

                    b.ToTable("TaiKhoans", t =>
                        {
                            t.HasCheckConstraint("CK_Loai", "Loai IN ('admin', 'sinhvien', 'giaovien')");
                        });
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.ThongBao", b =>
                {
                    b.Property<int>("ID_TB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TB"));

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TB");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.DangKy", b =>
                {
                    b.HasOne("DoAnMangMayTinh.Models.LichThi", "LichThi")
                        .WithMany("DangKys")
                        .HasForeignKey("ID_Lich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnMangMayTinh.Models.SinhVien", "SinhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("ID_SV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichThi");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.LichThi", b =>
                {
                    b.HasOne("DoAnMangMayTinh.Models.KyThi", "KyThi")
                        .WithMany()
                        .HasForeignKey("ID_KyThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnMangMayTinh.Models.MonThi", "MonThi")
                        .WithMany()
                        .HasForeignKey("ID_Mon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnMangMayTinh.Models.PhongThi", "PhongThi")
                        .WithMany()
                        .HasForeignKey("ID_Phong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyThi");

                    b.Navigation("MonThi");

                    b.Navigation("PhongThi");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.PhanCong", b =>
                {
                    b.HasOne("DoAnMangMayTinh.Models.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("ID_GV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnMangMayTinh.Models.LichThi", "LichThi")
                        .WithMany("PhanCongs")
                        .HasForeignKey("ID_Lich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LichThi");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.SinhVien", b =>
                {
                    b.HasOne("DoAnMangMayTinh.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAnMangMayTinh.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("ID_GV");

                    b.HasOne("DoAnMangMayTinh.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("ID_SV");

                    b.Navigation("GiaoVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.GiaoVien", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.LichThi", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("DoAnMangMayTinh.Models.SinhVien", b =>
                {
                    b.Navigation("DangKys");
                });
#pragma warning restore 612, 618
        }
    }
}
